### ISSUE TITLE
Release 6.0.0-M1 to Maven Central

### ISSUE THREAD

**Issue by marko-bekhta** [eclipse-ee4j/expressly#16]
Hey 👋🏻 

Would it be possible to push the release of Expressly compatible with EL 6 to Maven Central? 
Currently, I could only find one at https://jakarta.oss.sonatype.org/content/repositories/staging/ 

We need a Jakarta EE 11 compatible EL implementation for our work on Hibernate Validator based on Jakarta Validation 3.1.

**Comment by arjantijms** [comment]
Sure, I'll push it to central

**Comment by marko-bekhta** [comment]
Thanks!

**Comment by arjantijms** [comment]
See https://repo1.maven.org/maven2/org/glassfish/expressly/expressly/6.0.0-M1/

**Comment by marko-bekhta** [comment]
BTW @arjantijms do you know what are the plans for Expressy 6.0 to go Final ?

**Comment by arjantijms** [comment]
I'm not entirely sure. There's really only the updates for the pom pending. Perhaps that's simply enough for the final.

**Comment by marko-bekhta** [comment]
Hey @arjantijms  😃 👋🏻 

I just wanted to check in to see if there is any news on the Expressly 6.0 going Final. Thanks!
