### ISSUE TITLE
Push Expressly/releases/tag/5.0.0-M2-RELEASE to Maven Central...

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/expressly#9]
Please push `5.0.0-M2-RELEASE` to Maven Central as https://repo1.maven.org/maven2/org/glassfish/expressly/expressly doesn't have `5.0.0-M2-RELEASE` yet.

Thank you!

**Comment by arjantijms** [comment]
It's available here now: https://repo1.maven.org/maven2/org/glassfish/expressly/expressly/5.0.0-M2/

**Comment by scottmarlow** [comment]
Thank you @arjantijms!
